# Generated by Django 2.1 on 2019-01-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellquery',
            name='order_list',
            field=models.TextField(db_column='order_list'),
        ),
    ]
