# Generated by Django 2.1 on 2019-02-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_list',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_list',
            field=models.ManyToManyField(to='storage_project.Article'),
        ),
    ]
