# Generated by Django 2.1 on 2019-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellquery',
            name='order',
        ),
        migrations.AddField(
            model_name='sellquery',
            name='order_list',
            field=models.ManyToManyField(to='storage_project.Article'),
        ),
    ]
