# Generated by Django 2.1 on 2019-01-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0002_auto_20190105_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellquery',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
