# Generated by Django 2.1 on 2019-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0002_auto_20190204_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
