# Generated by Django 2.1 on 2018-12-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0003_auto_20181227_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
