# Generated by Django 2.1 on 2019-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0003_auto_20190207_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
