# Generated by Django 2.1 on 2018-12-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0004_company_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellQuery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=50)),
                ('order', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_project.Company')),
            ],
        ),
    ]
