# Generated by Django 2.1 on 2019-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_project', '0004_auto_20190208_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_contact_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
